# Generated by Django 3.0.3 on 2020-09-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
