# Generated by Django 3.0.3 on 2020-09-24 08:27

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200924_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to=post.models.Post.get_image_filename),
        ),
    ]
