# Generated by Django 3.0.3 on 2020-09-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20200920_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
