# Generated by Django 3.0.3 on 2020-09-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
    ]
