# Generated by Django 3.0.3 on 2020-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20200924_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
